#!/usr/bin/env ruby

require "turkish_support"
require "./adres-defteri"
require "./menuler"
require "./../yararli/terminalrenkleri"

using TurkishSupport

ad = AdresDefteri.new

puts "Merhaba, Adres defterinize hoş geldiniz."

loop do
	secim = Menuler.ana until Menuler.ana? secim
	break if secim == "E"

	case secim
	when "1"
		i = 0
		ad.liste.each do |kisi|
			puts "#{i.next}) #{kisi.ad_soyad}"
		end

		secim = Menuler.liste until Menuler.liste? secim

		secim == "E" ? break : redo
	when "2"

	end
end