#!/usr/bin/env ruby

require "turkish_support"
require "./adres-defteri"
require "./../yararli/terminalrenkleri"

using TurkishSupport

ad = AdresDefteri.new

puts "Merhaba, Adres defterinize hoş geldiniz."

def anamenu
	puts "Lütfen menüden bir seçenek seçiniz:"

	puts "1) Adres Defterinizi Listeleyiniz"
	puts "2) Yeni Kayıt Ekleyin"
	puts "3) Adında Arayın"
	puts "4) Soyadında Arayın"

	puts "---"
	puts "Çıkmak için E yazın"
	puts "---"
	print "Seçiminiz: "

	gets.chomp.upcase
end

def listemenu
	puts "---"
	puts "Çıkmak için E, Ana Menu için G yazınız"
	puts "---"
	print "Seçiminiz: "

	gets.chomp.upcase
end

loop do
	secim = anamenu
	break if secim == "E"

	case secim
	when "1"
		i = 0
		ad.liste.each do |kisi|
			puts "#{i.next}) #{kisi.ad_soyad}"
		end

		secim = listemenu until ["E", "G"].include? secim

		secim == "E" ? break : redo
	when "2"

	end
end